[bin/composer] quand on installe un nouveau module vendor ou qu’on update une copie des fichiers composer.json et composer.lock est automatiquement envoyée aux fichiers sources sur Windows pour les commiter + corrections sur la commande bin/copyfromcontainer

diff --git a/compose/bin/copyfromcontainer b/compose/bin/copyfromcontainer
--- a/compose/bin/copyfromcontainer
+++ b/compose/bin/copyfromcontainer
@@ -1,32 +1,32 @@
 #!/usr/bin/env bash
-[ -z "$1" ] && echo "Please specify a directory or file to copy from container (ex. vendor, --all)" && exit
+[ -z "$1" ] && echo "Please specify a directory or file to copy from container (ex. vendor)" && exit
 
 source env/dev-setup-config.env
 
 DOCKER_SERVICE="phpfpm"
 CONTAINER_ID=$(bin/docker-compose ps -q $DOCKER_SERVICE | awk '{print $1}')
 
-HOST_SRC=$(cd -P "$TRANSFER_PATH" && pwd)
-if [ ! -d "$HOST_SRC" ]; then
-  mkdir -p "$HOST_SRC"
+if [ ! -d "$TRANSFER_PATH/from" ]; then
+  mkdir -p "$TRANSFER_PATH/from"
 fi
-if [ "$1" == "--all" ]; then
-  docker cp "$CONTAINER_ID":/var/www/html/./ "$HOST_SRC/"
-  echo "Completed copying all files from container to host"
 
-  rsync -az --info=progress2 --delete --exclude='.git' --exclude='.idea' "$HOST_SRC/" "$OS_SRC"
-  echo "Completed copying from Debian to Windows"
+HOST_SRC=$(cd -P "$TRANSFER_PATH/from" && pwd)
 
+if bin/clinotty test -f "/var/www/html/$1"; then
+  mkdir -p "$HOST_SRC/$(dirname "$1")"
+  docker cp "$CONTAINER_ID":/var/www/html/"$1" "$HOST_SRC/$1"
+  mkdir -p "$OS_SRC/$(dirname "$1")"
+  rsync -az --info=progress2 --delete --exclude='.git' --exclude='.idea' "$HOST_SRC/$1" "$OS_SRC/$(dirname "$1")/"
 else
-  if [ -f "$1" ] ; then
-    docker cp "$CONTAINER_ID":/var/www/html/"$1" "$HOST_SRC/$1"
-    rsync -az --info=progress2 --delete --exclude='.git' --exclude='.idea' "$HOST_SRC/$1" "$OS_SRC"
+  mkdir -p "$HOST_SRC/$(dirname "$1")"
+  docker cp "$CONTAINER_ID":/var/www/html/"$1" "$HOST_SRC/$(dirname "$1")"
+  mkdir -p "$OS_SRC/$(dirname "$1")"
+  rsync -az --info=progress2 --delete --exclude='.git' --exclude='.idea' "$HOST_SRC/$1/" "$OS_SRC/$1/"
+fi
 
-  else
-    docker cp "$CONTAINER_ID":/var/www/html/"$1" "$HOST_SRC/$(dirname "$1")"
-    rsync -az --info=progress2 --delete --exclude='.git' --exclude='.idea' "$HOST_SRC/$1/" "$OS_SRC/$1"
-
-  fi
+if [ $? -eq 0 ]; then
   echo "Completed copying from container to host"
   echo "Completed copying $1 from Debian to Windows"
+  else
+    echo "Failed to copy directories/files"
 fi
