[bin/import-db] ajout d’un nouveau mode "consult" qui permet d’importer la base de donnée dans mariadb sans écraser la base qui est connectée au backend Magento 2. Cela permet de consulter et récupérer le contenu d’anciennes bases de donnés sans impacter l’instance Magento 2 + ajout d’une option au choix de backup de la base "magento" docker à l’import

diff --git a/compose/bin/import-db b/compose/bin/import-db
--- a/compose/bin/import-db
+++ b/compose/bin/import-db
@@ -2,50 +2,57 @@
 set -o errexit
 
 # Arguments:
-# $1 : (Optionnel) sql_file : Chemin vers un fichier SQL sur Windows à importer.
+# $1 : (Optionnel) consult_mode : pour ne pas écraser la base de données magento connectée à l’instance M2
+# la base de donnée aura pour nom le nom du fichier
 
 source env/dev-setup-config.env
 source bin/import-db-fn
+source bin/terminal-colors
 
 # Si un chemin vers un fichier sql Windows est fourni, on l'importe
-if [ "$1" ]; then
-  sql_file="$1"
-  if [[ "$sql_file" == *.sql ]]; then
-    import_from_windows "$sql_file"
+if [ "$1" == "consult" ]; then
+    echo ""
+    green "Importation d’une base de donnée en mode consultation"
+    consult_mode=true
   else
-    echo "Erreur : Le fichier $sql_file fourni ne termine pas par .sql."
-    exit 1
-  fi
+    echo "Votre base de données Docker va être remplacée"
+    read -p "Voulez-vous la sauvegarder ? (oui/non) : " reponse
 
-else
-  # Sinon on donne le choix au développeur
-  echo ""
-  echo "Quelle base de données souhaitez-vous importer ?"
-  echo "1) Depuis le backup quotidien de prod"
-  echo "2) Depuis un des fichiers backup .sql stockés sur la Debian (menu)"
-  echo "3) Depuis un fichier backup .sql provenant de Windows"
-  echo "4) Depuis la prod directement (attention à l'impact sur les sites)"
-  read -r -p "Entrez votre choix [1, 2, 3 ou 4] : " choice
-
-  case $choice in
-    1)
-      import_from_prod
-      ;;
-    2)
-      import_from_debian
-      ;;
-    3)
-      import_from_windows
-      ;;
-    4)
-      import_from_prod_live
-      ;;
-    *)
-      echo "Choix invalide. Veuillez entrer 1, 2, 3 ou 4."
-      exit 1
-      ;;
-  esac
+    # Vérifier la réponse de l'utilisateur
+    if [[ "$reponse" == "non" ]]; then
+        echo "Pas de sauvegarde de la base existante."
+      else
+        bin/backup-db "docker"
+    fi
 fi
+
+# Sinon on donne le choix au développeur
+echo ""
+echo "Quelle base de données souhaitez-vous importer ?"
+echo "1) Depuis le backup quotidien de prod"
+echo "2) Depuis un des fichiers backup .sql stockés sur la Debian (menu)"
+echo "3) Depuis un fichier backup .sql provenant de Windows"
+echo "4) Depuis la prod directement (attention à l'impact sur les sites)"
+read -r -p "Entrez votre choix [1, 2, 3 ou 4] : " choice
+
+case $choice in
+  1)
+    import_from_prod
+    ;;
+  2)
+    import_from_debian
+    ;;
+  3)
+    import_from_windows
+    ;;
+  4)
+    import_from_prod_live
+    ;;
+  *)
+    echo "Choix invalide. Veuillez entrer 1, 2, 3 ou 4."
+    exit 1
+    ;;
+esac
 
 if [ $? -ne 0 ]; then
     echo "Erreur lors de l'importation de la base de données"
@@ -53,6 +60,6 @@ if [ $? -ne 0 ]; then
 fi
 
 # Configuration de la base de données
-if [ "$USAGE_MODE" != "install" ]; then
+if [[ "$USAGE_MODE" != "install"  && "$consult_mode" != true ]]; then
   source bin/after-import-db-config-inc
 fi
